### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "e389e4c104a345558d9a923404d96b82",
  "accountNumber": "1000000003",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/d566c99d10c84a1ba41711ab8183c5be